# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["ehci_pci" "ahci" "isci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  boot.supportedFilesystems = ["ntfs" "bcachefs"];
  boot.initrd.systemd.enable = false;

  boot.tmp.useTmpfs = true;
  boot.tmp.tmpfsSize = "50G";

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C23E-6883";
    fsType = "vfat";
  };

  fileSystems."/bcachefs" = {
    device = "UUID=4b321075-5391-437a-ac5c-c33fab82c9e3";
    fsType = "bcachefs";
    neededForBoot = true;
  };

  fileSystems."/nix" = {
    device = "/bcachefs/nix";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home" = {
    device = "/bcachefs/home";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/opt/steam" = {
    device = "/bcachefs/steam";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/opt/gaming" = {
    device = "/bcachefs/gaming";
    fsType = "none";
    options = ["bind"];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0f1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
