#!/usr/bin/env bash

is_today() {
  [ "$(date --date "${1}" '+%D')" = "$(date '+%D')" ]
}

get_dom() {
  timew get "dom.${1}" | tail -n1
}

while IFS=": " read -r key value; do
    if [ "$key" = "temp.report.tags" ]; then
        tags=${value//","/" "}
    fi
done

if [ "$(get_dom active)" -eq 1 ]; then
  echo "ERROR: There is a running task. Please use 'start' instead"
  timew
  exit 1
elif [ "$(get_dom tracked.count)" -eq 0 ] || ! is_today "$(get_dom tracked.1.end)"; then
  echo "ERROR: No tracked tasks today yet. Please use 'start' instead"
  exit 1
else
  # shellcheck disable=SC2086
  timew start :adjust "$(get_dom tracked.1.end)" $tags
fi
