#ENC[AES256_GCM,data:OWp1a2xvyoRamMWCasmtnxKTFnIVwLRmjJVUcC9I5aH7ZP01EOg=,iv:heuHzi4rpulwDA6CyGLA1tRTcXtv1keaQ4Y+MMuEZq4=,tag:omJMAQMcc3cLfatHTNzDNA==,type:comment]
example-key: ENC[AES256_GCM,data:Mog+Rqe7l3ppqxvDfA==,iv:LugmmoZjy1sZf3e9CkjDYADCrUC0mU8ALo/89te4Nzg=,tag:X+bBsKcEjIOiXD/4vhJIUQ==,type:str]
#ENC[AES256_GCM,data:LlUw+gKanYlcZ64klFpal3mP/zo3KM8Nl07B9pceBHg8aYhaCJpORo/z6XIPjIY4tIE3ENO9sZw=,iv:mcjFSbN9/6ZlMp4PC8N9C1tDCUSRVFJ9Yx+APGRx7II=,tag:w9cGNAYSR9TRjctYcUMNOg==,type:comment]
#ENC[AES256_GCM,data:n9W7JkHhVgYC1b5RhGd/s94H8M1D7qzVrUX7yW7MrCOSEVgNmWDeGzUUzsGkKbl1F+Ry4kjOJE7Xt8qNls2iT51FE/xnFHcu,iv:4UxTx7u/fHvKvK+3llfrr7AMGxv9X8Trac3CixL2DHo=,tag:tf30FPBGbwUBfoBbesxXhw==,type:comment]
myservice:
    my_subdir:
        my_secret: ENC[AES256_GCM,data:TQGqnEPbcAQD,iv:+JDY/pTy2NOVCttcOHKhaT6Cp2GTI25tdbg3E2cU8sU=,tag:CvkjjH609XEhu/cYos9/Rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18uwq53hx4da5zhq27vpy8e62vxzm2hvdh96uqqyht4u98sl45egqjaeexe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQkJ4dVRpWWdidHNEaVVR
            d2FCa3dqOXpJVzJJenU3NXJWVXlBZWg4TnlFCnpYRndlbHBkMzBPS0dpWDdHYmth
            cEt3bmlFWitvcmc4R1dINTBvejhVWVEKLS0tIEpUTE1DWGFGcW1WbVZzK2xaanZl
            TTJjR2tMSSthZ1htSVdmRWtUb2tuRmMKshTZD4Vjx9uvPjhuq3cy9Lw55lC8Epag
            fji5PEOiulcJrOyHdEJ0TGKAlYGcOwkGkpScxBD82pSibFpmEEP40g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aaeef4kyxdptp9f04lxt4nwcwmvdg5lgkkqzc6txa08avly3cygsgz2zc8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJT3FsQWt4Sm54UlpUUkho
            TnlyS1BCa3VBSnkrUFpFWk5rc0ZHQThKc0RnCm1jalhodnF0WlN1elZTV2NwL0R0
            dWVTRVhSd0NmaGRKVWVPZ2pvaDN4ZGsKLS0tIEo2Nkk1ZlQxQlV3Q1BpMGc2OERZ
            T3RhSjdDa0dhTXlxUU5PN3hhZWlCdzgKZjjXYnUzc3ExdkiQQ73ZrL1G8kgHHqBn
            kWXg91i4COGolOkPJca0y0NRA8D5qW5Bc9454n+cBqWkcXe4HrfYUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n8mwpevs6qys0em43vcca5mnztsw4vpmng80yvke75axag3w5ymsh8kunc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ2pLUHZMR2JUbDFubGg5
            VkVGZ2djdGpidGJDSk9wL1ZFZ0xmS2VZWEVNCjdhMkx0aXFtNHdNUHVCa29TMHZL
            dG5mSENmMGtFSUZlWnZtQUg3aXBJN0EKLS0tIENHQnVsQjhzd1pxcVJRaU45MEpZ
            U2FJT0JRRjNQczlPejVLaTZQUXRqa3cKPUS6NHOZfBWtvCPmZY0kotUdDR/S3Q/C
            iOJ66nTlMmW28srF0sCGyJChP3YPPndscCWS53Kc7BUGm0VvC2o8jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T18:52:42Z"
    mac: ENC[AES256_GCM,data:pg5ciRsl9XL6vJ629IBKRYKHReHPBlyuldEvG4z9GZpNXkpvYSJTX9diaetLR+xCu5XVEI3jJKCnmh4o3fC11jGQ+DuktwI4q08uoKKyQbA/G3BZXwgUVgtk6wgryK8BUt4TDhQEZVaVeILhdr259ga6cHdhQ7kLubXsRbWzcsA=,iv:w/NbD/fX7/0huvmYe62JLS8dW/aq16SEdRIZmgb4HeU=,tag:eCykD9AcgcgVyEuGlri1nA==,type:str]
    pgp:
        - created_at: "2024-01-29T19:03:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1XuZDLZaB0BAQ//e43gHVv6d+gImdkdI1mZ4pERX1JwDOCsenG9490HfcfC
            0dr5RIGhPPqtBji3QEfsLTxr6igopa6Y5v+Pvl79Y8ARLOWq7mgFYVyVG2unrLRG
            YZpGtQlz4I9EzUgQbFzp1znsu2QadhVEBYznhHDA5Jg5SpBGsnfhuQ0ux6YJMKCJ
            e9TF5UyrascW2WNQKFVTkNsi4XyyyKvs89hJ3pMDB/No3t3/6R21M8LJAgbhg9ZP
            cTQ+PaNvRGsyqD40ooWD+yY9PQOhrvxYnXqWZAnnlX4gcy1R7K0ACDSPqN3g81nq
            M8ZVhwiYPo3v1rpTlMWxl3zHcCi95B8NWxa1u8UfAg8a2AdeBXtRj9cyl46vXy8U
            JdkttFga1INmd3ovK/JB8jPj8QfYzqIi8HeIbEirZhqqmQuRnWUzBMEUwrdZAM/M
            MdLn3OLhuWf3EB1mFRRQE+W6BDQ2gD6TZp0wCzp22sT5xJ+hS09LkpKMWDoAHQum
            L08nxbyo3i+cUToxrLN+W35tKdCdGUXr1RAAseQHLETZBV1gdgaZSFLksryYm94y
            1132e/iOtLlvWCWN0rax5SD/PO9YTVoO5QZYh4pyrRwh6Mxwom3HPtaZ4NBHmpPB
            VjYBd2eYqBghBtFaO5TbLVXmGLt7qSVDKdKkPPY0SrvLz/3Z0IxU4JtzMxna81bS
            XgGBLx0s4Y4eDlvrLTAzOGJOzvE1fidI9Xdz4djdec4V1DSUH0NOnqv4Dv73y2Ga
            G46csBaqefrEVfF2paTafgGdA/u4WgPKIMfm5jsLBGzI5DFCwWrn+wcZUotTa8w=
            =qvnZ
            -----END PGP MESSAGE-----
          fp: B8D2F3121A85E40612A7FD7082CEF915A63BA766
        - created_at: "2024-01-29T19:03:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3V9a/im4q3WAQgAhQzD8LObrn42HZMTL1Jd/ZN/cy81PJtejlFyJDul7J8K
            hGdQIIMCk4UJ+ReWS7N15kIN0PtUKJJTkYc9qoJCivwxQN9mFtg2tuRolh5qHD0R
            J/39lFFvw01hpH8qsB1fyWPsrCKEsKw3dUdfFR1InzC3r2OH5VhyQNBICXDbZfYE
            WW7beGnB/JbNXAWChKpMWxyjjjW4P97aniIPwoEOTh/D2ZNboC/Qx9TuJ7y/BSL1
            rjBWP1bDPY8EHxJzGDo4zs4DsXfh7Mu3WctEbSxGaklOszV+WuTlyGFVWGfuZCGl
            I5XeOJGW/bfWF9QV/lVf3Ibiy2n4T+FvqbgDY/vzcNJeAQWpqHx8XlYPyz0nC8zm
            /zO0vHXcjGJufWHXpnHx54xx2IsP4GkL8jbiV3fNAKQWSHUovPSPb5Ne1+PtxBTP
            n1LJ0u4yzf5RAwQkjyxQqNfbzBzGIu0Tawny8oBQqw==
            =dXL4
            -----END PGP MESSAGE-----
          fp: 8D4762947205541C62A49C88F4226CA3971C4E97
    unencrypted_suffix: _unencrypted
    version: 3.7.3
