#ENC[AES256_GCM,data:OWp1a2xvyoRamMWCasmtnxKTFnIVwLRmjJVUcC9I5aH7ZP01EOg=,iv:heuHzi4rpulwDA6CyGLA1tRTcXtv1keaQ4Y+MMuEZq4=,tag:omJMAQMcc3cLfatHTNzDNA==,type:comment]
example-key: ENC[AES256_GCM,data:Mog+Rqe7l3ppqxvDfA==,iv:LugmmoZjy1sZf3e9CkjDYADCrUC0mU8ALo/89te4Nzg=,tag:X+bBsKcEjIOiXD/4vhJIUQ==,type:str]
#ENC[AES256_GCM,data:LlUw+gKanYlcZ64klFpal3mP/zo3KM8Nl07B9pceBHg8aYhaCJpORo/z6XIPjIY4tIE3ENO9sZw=,iv:mcjFSbN9/6ZlMp4PC8N9C1tDCUSRVFJ9Yx+APGRx7II=,tag:w9cGNAYSR9TRjctYcUMNOg==,type:comment]
#ENC[AES256_GCM,data:n9W7JkHhVgYC1b5RhGd/s94H8M1D7qzVrUX7yW7MrCOSEVgNmWDeGzUUzsGkKbl1F+Ry4kjOJE7Xt8qNls2iT51FE/xnFHcu,iv:4UxTx7u/fHvKvK+3llfrr7AMGxv9X8Trac3CixL2DHo=,tag:tf30FPBGbwUBfoBbesxXhw==,type:comment]
myservice:
    my_subdir:
        my_secret: ENC[AES256_GCM,data:TQGqnEPbcAQD,iv:+JDY/pTy2NOVCttcOHKhaT6Cp2GTI25tdbg3E2cU8sU=,tag:CvkjjH609XEhu/cYos9/Rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18uwq53hx4da5zhq27vpy8e62vxzm2hvdh96uqqyht4u98sl45egqjaeexe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdjlPaWpSMHVpNGUyRzVU
            ZWo3bURVVytOelI2Sm93OEdwaVgxbFl6Y0drCldxN2QrVTlDMHg3TmNqRlpFUzha
            dXQ3RkV2SjcxaXMyM3dFRHVXWWI3ZWMKLS0tIHl1c2VsQmFmUU1CNGNYdVpZOVJr
            UlA3cUlFcU1Qa0xtMlAzclBNKzEzQVUKP4o9zjR58VhtyR+S0hquzYVM8qbQrjlz
            sByTbS9A1Cuzso2KsbmoVqbNSFU0HmUlFf+r7qZN0oiBPjdCdJ5eQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T18:52:42Z"
    mac: ENC[AES256_GCM,data:pg5ciRsl9XL6vJ629IBKRYKHReHPBlyuldEvG4z9GZpNXkpvYSJTX9diaetLR+xCu5XVEI3jJKCnmh4o3fC11jGQ+DuktwI4q08uoKKyQbA/G3BZXwgUVgtk6wgryK8BUt4TDhQEZVaVeILhdr259ga6cHdhQ7kLubXsRbWzcsA=,iv:w/NbD/fX7/0huvmYe62JLS8dW/aq16SEdRIZmgb4HeU=,tag:eCykD9AcgcgVyEuGlri1nA==,type:str]
    pgp:
        - created_at: "2023-06-29T20:36:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA1XuZDLZaB0BARAAp5i2yLSHT1rPrPCAg74j1E0T8XDCzHQzOQo3KVGgT/XF
            B8HLAkxFem8ppkb9JIW1AYZqbxDFkKUY9eEaifvuXm6UbPTUzElb3deGwDsoE6NQ
            38OBStRVny+9ADavFlmudN1/Ss7NWz2cax8NJSOGOy5XZZZ7jGqqrndyvJKPrjr+
            9xw06w5fAxjvh0NX7W9/afHJ2l/Q7SCqgOJTLp5Z7kE9bWGdQfZ+bXi1yas+lsZX
            JP0fjHJPRVKGlsEpj5EPjE6VtmdQDct7o6IRlUO3f1llx4FAA1JdjjBWiserGhZd
            HiUKNwMHFjW7p1yfUZH03kRjqd04dvcxBkwYQQWZXcU7OOQnXrHOhp5wh2pLuEdo
            MTx1V0NoZ2OOV22WzOLN5d9GOcN6hjhpJSa5blccQ/zIsDZlOv1YtfsDbXPLq1kr
            W3QvRzokigM0qzRZR05Fs2iMJbzty105hZsDuotdF4cvoFF+qa4/ogkSgOD5zs5C
            FH48X/6b6soV624a7p/tbj+4qo1YYvCT+VhI4D88K2633nEuzA17XrlnguTsayva
            +Ps0d91TPqnWrAacIT/ht/5tmnueFntgyi4+e+ZcCUN9RIvM4pOBxgGRqomLsZN1
            3tuvTQQ1BvCwoGBZIa+eHdELebJW7HMMQhdWn9BtZRRZWBSjpK+uYmSCjK0yFJHS
            UQF9lt1K+Sl9XSvZSpXOGJS/ZHBI30BAnZd9iaPFpcNBa/lyMPHMfBfcOgHobD9y
            G5y4TOj6l34DBfZKOfX1H8q7RF7jSw+kvJBhmIXfUriZDg==
            =MNgm
            -----END PGP MESSAGE-----
          fp: B8D2F3121A85E40612A7FD7082CEF915A63BA766
        - created_at: "2023-06-29T20:36:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA3V9a/im4q3WAQgA0GF/IJ1q78IIhJFVMToY0LzyV6v0CvE7pOdUCaLWvzv9
            /q9DwWKRUjEdICfGz8Ye+TdZMvoXH/E3S8k6hpg0S6+ilyQ74diXCWcVqMS/01iN
            LJRRZjv3zKVZmcDde9Oq1GYNo99YaI8d3pjK5JHAWphfvXCqIoC7h6KRZD1HaCb2
            UMbVYeaj38ScMAQ/phLfXKOMdcWsHRIAOWCUb8BuilOvnSza1PVZq8Vbw87EjHQn
            bQ/RIUw1iUDaAlK4eOUZYPmxSQ2TgXVOkZIT8Q1CgG1yLRaTID382TBLzYz5ika9
            /aPZovgf0Q0X8EPSFquYobifZeC+ajjMo3p+Z6sWtNJRAScCSwmOmcMi9Z0gx4QS
            HCpFRqii13cT06sRlFowNuSiaVecee5ZO31uLI0rqWEBWrGXNOueMxodD2WE8Yk5
            T5UvShN7h89qN9UNRhZx730V
            =D5ZN
            -----END PGP MESSAGE-----
          fp: 8D4762947205541C62A49C88F4226CA3971C4E97
    unencrypted_suffix: _unencrypted
    version: 3.7.3
