#ENC[AES256_GCM,data:OWp1a2xvyoRamMWCasmtnxKTFnIVwLRmjJVUcC9I5aH7ZP01EOg=,iv:heuHzi4rpulwDA6CyGLA1tRTcXtv1keaQ4Y+MMuEZq4=,tag:omJMAQMcc3cLfatHTNzDNA==,type:comment]
example-key: ENC[AES256_GCM,data:Mog+Rqe7l3ppqxvDfA==,iv:LugmmoZjy1sZf3e9CkjDYADCrUC0mU8ALo/89te4Nzg=,tag:X+bBsKcEjIOiXD/4vhJIUQ==,type:str]
#ENC[AES256_GCM,data:LlUw+gKanYlcZ64klFpal3mP/zo3KM8Nl07B9pceBHg8aYhaCJpORo/z6XIPjIY4tIE3ENO9sZw=,iv:mcjFSbN9/6ZlMp4PC8N9C1tDCUSRVFJ9Yx+APGRx7II=,tag:w9cGNAYSR9TRjctYcUMNOg==,type:comment]
#ENC[AES256_GCM,data:n9W7JkHhVgYC1b5RhGd/s94H8M1D7qzVrUX7yW7MrCOSEVgNmWDeGzUUzsGkKbl1F+Ry4kjOJE7Xt8qNls2iT51FE/xnFHcu,iv:4UxTx7u/fHvKvK+3llfrr7AMGxv9X8Trac3CixL2DHo=,tag:tf30FPBGbwUBfoBbesxXhw==,type:comment]
myservice:
    my_subdir:
        my_secret: ENC[AES256_GCM,data:TQGqnEPbcAQD,iv:+JDY/pTy2NOVCttcOHKhaT6Cp2GTI25tdbg3E2cU8sU=,tag:CvkjjH609XEhu/cYos9/Rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18uwq53hx4da5zhq27vpy8e62vxzm2hvdh96uqqyht4u98sl45egqjaeexe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweE9XNE9SZHA2N3BFVmN3
            N2oyU0VKR3pDN1RrVEZGRzQzNFh6em93VFJRClp0b2xpZnl0Qll2VWI0VEk0YStz
            ZFk2NFcrUUV3YTlqR1p1R1RIV2poVm8KLS0tIExuNW1sbUJaVkZRSGdzalArcGg4
            N2NUQlJMK3RHc2VjdGhUWGlMdXVnTkUKMA6Tl3Iiq+dfPv5/s0U3LxRajWdA1OHB
            1hKBHBI+QyXWRJwA/nFXrpgL5UnJeeoQ5suw218uotv89b3MepU8XA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age125l0n4ucrvpvg82pu9ftpdu55rq4we24zncw92nvw30eyg50jcts9chj8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SHphYjQxRVRKSXpHd1d3
            blJWK2NLSnV1VHdxOXJTWkNTSHVtRzFFc204CnhVL0Jld0g5T1NPQ1l5SnFSZ01Q
            aFNwSm5xMXpEOENHR1BSTFZLZjJudzQKLS0tIHhiaFFWeStIaFUvSFJvSXJKVTl0
            Z054WEVzUnc3S0N3Qi8zSGc4cy8rS2MKPwv6Bqqv6RO4z8E4WoIcCekmIuxa+jfv
            NzbSrPnlK30lFqPwPCdWal1NsjXlhlyJwoKyKClIWQu39ZVLOm26gg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n8mwpevs6qys0em43vcca5mnztsw4vpmng80yvke75axag3w5ymsh8kunc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbGJ4a25aWTZUb3dpSjRY
            eHljUFVQT0E3dldIM2tTdXo2QVExUjFGS1dRCkVTTkxUV205Ukk2ZGpSS2xzOWkr
            WFRzVFRLaURiVEowZVZFT3lqNFFKOFkKLS0tIHpsTFJ2RjZWSDJva3dLbFFUSWhT
            bWErRHkvOHZSM2EvajRqWjZEamZHeGcK5oWTS8G3ytcn62fa3SSD0ni9VLFZqAFy
            YjAedNaZMkOO//lImbv2kr10qeb54KXqTyHVVcdnXxQPJOaTBPa0Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T18:52:42Z"
    mac: ENC[AES256_GCM,data:pg5ciRsl9XL6vJ629IBKRYKHReHPBlyuldEvG4z9GZpNXkpvYSJTX9diaetLR+xCu5XVEI3jJKCnmh4o3fC11jGQ+DuktwI4q08uoKKyQbA/G3BZXwgUVgtk6wgryK8BUt4TDhQEZVaVeILhdr259ga6cHdhQ7kLubXsRbWzcsA=,iv:w/NbD/fX7/0huvmYe62JLS8dW/aq16SEdRIZmgb4HeU=,tag:eCykD9AcgcgVyEuGlri1nA==,type:str]
    pgp:
        - created_at: "2024-01-30T10:19:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1XuZDLZaB0BAQ//XsrO+IkFmCXMeE31wuyvcw4nBFF7okYkBX8v0vW5mLLZ
            V3aE57V0Rom22FlQZB+GRpz7EbtneyZ5m393omQWIr7Bv62mowaxMD9LNdCYi2g7
            FmFmAvNG0Uf+/hpogV11rJ7u4lKuoj0+sVgnN2JRoyuJVg4pgHIbkeJg0gSXcq/g
            vfFoye8VQy7f65+EK8w+9E7J8tAdNTULcXGjLTl3dQSp99DoXZ0WqTzaPIfO1eNL
            tnB5SxJQtmo7SwbHWnu0t4jibu9EqtkjzDM01T0yJ4e8MIpRX0y0gL8mWiWyzM0Y
            CbpMBt+OpkNwp4vM21C5UMb0+oAQLoddTsLfV5HnBHf9WWEMvVCDh5EhKVTTM8mS
            bHgCt3wjILEd6FC3H++fDhmmbBy1dMuQTNfOnkx9dOPMWJoM4smTz/KIH0uMQUzm
            EAR+wLFWAkzF0lDpMXFTVZy10zc+4ULQmlYjgQd8nsIpmSWQNCm+uDivY5ZELH9W
            SVfmxgQ1NtQFAVis8Rz+OgdCrT+1dRCpW/uxsfli8WyJHGoFLwDPOnf1xAHShWsQ
            9Oc4RcmN2/XNXmeMmswj0LNtWG9siA2rUOjbeQm+wH2LfjotYpwro7XNsN2TWB4f
            7JKcZB7Ry6FD9K/qIH7jQWzBUDMZcU+yDuPiMKlO1hJjwAwBBAsOqx0GRzo5n8bS
            XgFWwVsoZTo19Wfy8vN83zaA/OAllYn5G6iMfONq2Sm32acgc2QbE4H5JaL53XJU
            Ehyt7sDmcwx+bMobceGUrB4cJoE/e1tn9aDdgZ6nSrFEaQcfGAqIbMa0Wksngag=
            =5DWl
            -----END PGP MESSAGE-----
          fp: B8D2F3121A85E40612A7FD7082CEF915A63BA766
        - created_at: "2024-01-30T10:19:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3V9a/im4q3WAQf8DJ4/3b+HmcQU++trXPsDWgQhMKlPLLQrUF4g6G94uVmp
            U9RJeYtGAiqBF9HLBQQ2Icr0MN7fSAv50HT+MlSV+Ny0UvDyMnLx1/8aEbGNaORu
            09pKDb3KSnB+TlB0xEEWcugS6yhLVwOIAyPRuQ/NCvyFtDZVv/aFYR9T/rJlUApn
            cKpIH5VIkNNA9SxaQGCBUfOq88cuxoy3OcIInx6Behqd/3PhLjZwlNn3q1J2YBYG
            E2GAAEqE5Z4YKM7NxDs3PSme3/68kZt2Tndz3SLx0qit0ZoBBAe0a4eH6YMen8xt
            7O6O6XFEfksguqgscB3EwoDd7gzvil5RW5+pR2OnUdJeAYGekZV4wjmXJCah2U+6
            0F7Ruva/Yo3J/nBIIR+AiBMPtK+vGpQfjs+H8fs+CcCxGGmc4lmXQtd7sx2BeLkb
            LDoLY3QnA2ix1FS1/MURWKPeiMGDXVONi2pD5FClAw==
            =3UyR
            -----END PGP MESSAGE-----
          fp: 8D4762947205541C62A49C88F4226CA3971C4E97
    unencrypted_suffix: _unencrypted
    version: 3.7.3
