#ENC[AES256_GCM,data:OWp1a2xvyoRamMWCasmtnxKTFnIVwLRmjJVUcC9I5aH7ZP01EOg=,iv:heuHzi4rpulwDA6CyGLA1tRTcXtv1keaQ4Y+MMuEZq4=,tag:omJMAQMcc3cLfatHTNzDNA==,type:comment]
example-key: ENC[AES256_GCM,data:Mog+Rqe7l3ppqxvDfA==,iv:LugmmoZjy1sZf3e9CkjDYADCrUC0mU8ALo/89te4Nzg=,tag:X+bBsKcEjIOiXD/4vhJIUQ==,type:str]
#ENC[AES256_GCM,data:LlUw+gKanYlcZ64klFpal3mP/zo3KM8Nl07B9pceBHg8aYhaCJpORo/z6XIPjIY4tIE3ENO9sZw=,iv:mcjFSbN9/6ZlMp4PC8N9C1tDCUSRVFJ9Yx+APGRx7II=,tag:w9cGNAYSR9TRjctYcUMNOg==,type:comment]
#ENC[AES256_GCM,data:n9W7JkHhVgYC1b5RhGd/s94H8M1D7qzVrUX7yW7MrCOSEVgNmWDeGzUUzsGkKbl1F+Ry4kjOJE7Xt8qNls2iT51FE/xnFHcu,iv:4UxTx7u/fHvKvK+3llfrr7AMGxv9X8Trac3CixL2DHo=,tag:tf30FPBGbwUBfoBbesxXhw==,type:comment]
myservice:
    my_subdir:
        my_secret: ENC[AES256_GCM,data:TQGqnEPbcAQD,iv:+JDY/pTy2NOVCttcOHKhaT6Cp2GTI25tdbg3E2cU8sU=,tag:CvkjjH609XEhu/cYos9/Rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18uwq53hx4da5zhq27vpy8e62vxzm2hvdh96uqqyht4u98sl45egqjaeexe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMjBLZVY3bnhXT2JPRTA2
            Kzh0dEovK1hEZ3liNDBVSHIrZ2xFdi9vcEM4ClNqWHVKL01IcHZJN3ljNmZEODhO
            aFJyMUw4MWNGOURTUXBLSXlwRUF1R28KLS0tIHFpdjBzRnZ5Yk1jNk1TaTNaYVdB
            Y20ydEVOaEJWakxzRnhtUlA2SkF4TWsKj8la87zw9eIwD7L6AEusSxcQmM1SPYAH
            Fqr1fUU4LA00lYyHlU675+80b47UbzZCGvov5qlEY0T8Un+fSOTNWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aaeef4kyxdptp9f04lxt4nwcwmvdg5lgkkqzc6txa08avly3cygsgz2zc8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTFhkcGc2OUlRSEFzc0lT
            R1NNYzRhY2FlUTI4dktlN0wveUFjbUdtbTNjCnRQWVVPUkVWTmkxcHJiTXYzT1Rk
            Vi9vZ0VUTGtQMk5LNnM0ZHBUMWMxWEEKLS0tIFNYMWtzVXZkSzNWOENKQ29raGtL
            L3lvYmZiK0ZjTUNwVkhPQndTTjdKaWMKGRf2TRqfXbRWpPRhGsrpNE0oyDN9UtDJ
            46c7ZN3gi4OQs7bZix4OAoLFuF+LLToPhVk7XExNfkgOBvMJx8JxMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T18:52:42Z"
    mac: ENC[AES256_GCM,data:pg5ciRsl9XL6vJ629IBKRYKHReHPBlyuldEvG4z9GZpNXkpvYSJTX9diaetLR+xCu5XVEI3jJKCnmh4o3fC11jGQ+DuktwI4q08uoKKyQbA/G3BZXwgUVgtk6wgryK8BUt4TDhQEZVaVeILhdr259ga6cHdhQ7kLubXsRbWzcsA=,iv:w/NbD/fX7/0huvmYe62JLS8dW/aq16SEdRIZmgb4HeU=,tag:eCykD9AcgcgVyEuGlri1nA==,type:str]
    pgp:
        - created_at: "2023-07-24T16:40:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1XuZDLZaB0BAQ/9HN3fJMEJGnJoINQG/Stk+yFXWVT5mDvMRcJvRpPZvVYy
            /BIvTcNBhyvN+vX+IJsfTUDuJsR8TNuqD4ohvamTEanKYkGprQojpYxtoQFSWMS5
            Qbnkq7JmId4WfckpKKxvO2n/HA4xiH8hDaRcvmVM8/LH5FUPhTJaJMv37Q8D6Ujd
            twmiZb6mcKiW6MpDb/T6dpOHf4N8eHrtdQyi6PdVmvrdNWl+H8E8Y/mfXJS42fzo
            v2yZ0JIVfK4pSvVe6ahIZ5Rb4MEaLUa7s7WMF3AlfqH4Ff4/mRtq4rFwBKVOA4HU
            EKQyFvvxUtSS+4rGcsPYZIb6rk43i+s/Bi/9+s1QcpN8m1U/pSEKWVfVGYRwyOd7
            IlqwdH+7LENon3KGYVe5UEYYwsyKM14eSyzavjWxFe4X79QKDGDc01m5cx00PUFC
            mP7aWdFX9s8aikIwkPiIWMfmz8WfWuvgSX12RxVdMPDZkSnMfp1iSfaa2jhZWPXG
            AEZBlnP5Hb6YNavOHHT4SOKctIsZGk+iVE4gjK97lVKs2UYslcEGgbVxJFzfBzf4
            q1DSK+WRtS3D8MW+hdBYvN/uidrMyBYU878HDni0T/jaIjZhgCMoMkRTzlPx+bDZ
            kvUlDrOGGpi8hM3AB7eAHrMJcPGm+QpGpAj4rV34llJyFs4j79G317ixuhtAfcLS
            XgEO/YcF1lBcMWeaNZNScsP34zhRtb9UL+Hm1XOMlw3kFjpnhTtM/5nRZgchtHPm
            TE4h/ZcHR7N1bP4NdFa0cw9nuREZ+J6GXt4u22LRK8rZRcs3njxyBhg7gt/c9QA=
            =BPxN
            -----END PGP MESSAGE-----
          fp: B8D2F3121A85E40612A7FD7082CEF915A63BA766
        - created_at: "2023-07-24T16:40:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3V9a/im4q3WAQgAhqvsL0JwEW6WkLDh3kQe+/i+P8uy+A9qfv6I+0uUb/Qk
            kWMxCNBjwMFYTBJFOFvVoMlaNUsFYPQgIJM5fLiHWCDhx+Y2dfCkBfDLclAgxUDi
            9B0zdeI7u+xKSCz/u4fScvrfNRgg634m5k99NFaHxbH3VakGWsGf0pl4qOm5ZlkR
            VFLwcd5rORNN4j9pywpBZsNUzkLNElPgjB5W3men9T+NJSFEChFSY0fTUuuitUxH
            DJnu5vV8XnrPmibu+A297ozUOJr9h5KVi0zeJDVYjmbgJay/bda/V02JGBNMweCl
            mxwOj3GiNfcynna8phm4exZCSG5xMVxE+U4vdIe4q9JeAchBMRPsU9gztY0sJWFq
            M8NyJQmofVC6KdpGM0quBqxidWSZePA8EBUYAQUDEqS7Hutz52Ifp217L+lRfTed
            zynCRWYmLjrt4ryoj+AQ9rwYc/zioQ1klwM4VwlT7Q==
            =rTnn
            -----END PGP MESSAGE-----
          fp: 8D4762947205541C62A49C88F4226CA3971C4E97
    unencrypted_suffix: _unencrypted
    version: 3.7.3
