# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  networking.hostName = "nix-stick";

  boot.loader.grub.device = "/dev/disk/by-id/usb-Samsung_Flash_Drive_0374218070021442-0:0";
  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e2805613-f0a0-46ce-b419-33a32da7ca03";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."stick-root".device = "/dev/disk/by-uuid/258f07da-ff42-4df7-a573-e4c21ace1afd";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9485-0DA5";
      fsType = "vfat";
    };

  swapDevices = [ ];

}
