#!/bin/env python

from pathlib import Path
import subprocess
from blessings import Terminal

def get_untracked_files_in_home():
    yadm_files = [Path(line.decode('utf-8')) for line in subprocess.check_output(["yadm", "ls-files"]).splitlines()]
    for child in Path.home().iterdir():
        if child.is_file() and \
                not child.name.startswith(".") and \
                child.relative_to(Path.home()) not in yadm_files:
            yield (child.relative_to(Path.home()))

def is_repo(dir: Path):
    gitdir = dir / ".git"
    return dir.is_dir() and gitdir.is_dir()

def all_children_are_repos(dir: Path):
    for child in dir.iterdir():
        if not child.is_dir():
            return False
        elif is_repo(child):
            continue
        elif not all_children_are_repos(child):
            return False
    return True 

def print_relative_path(path: Path, relative_to: Path):
    print(str(path).lstrip(str(relative_to)))

def get_non_repos(dir: Path):
    for child in dir.iterdir():
        if child.name.startswith("."):
            continue
        if child.is_dir() and not is_repo(child) and not all_children_are_repos(child):
            yield child.relative_to(dir)

if __name__ == "__main__":
    term = Terminal()

    print("Directories that are not version controlled:")
    for d in get_non_repos(Path.home()):
        print("\t", term.bold(term.blue(str(d))))

    print("Files that are not versioned by yadm:")
    for f in get_untracked_files_in_home():
        print("\t", term.red(str(f)))

