plugin:
  # See https://k9scli.io/topics/plugins/
  raw-logs-follow:
    shortCut: Ctrl-L
    description: logs -f
    scopes:
    - po
    command: kubectl
    background: false
    args:
    - logs
    - -f
    - $NAME
    - -n
    - $NAMESPACE
    - --context
    - $CONTEXT
  log-less:
    shortCut: Shift-L
    description: "logs|less"
    scopes:
    - po
    command: bash
    background: false
    args:
    - -c
    - '"$@" | less'
    - dummy-arg
    - kubectl
    - logs
    - $NAME
    - -n
    - $NAMESPACE
    - --context
    - $CONTEXT
  log-less-container:
    shortCut: Shift-L
    description: "logs|less"
    scopes:
    - containers
    command: bash
    background: false
    args:
    - -c
    - '"$@" | less'
    - dummy-arg
    - kubectl
    - logs
    - -c
    - $NAME
    - $POD
    - -n
    - $NAMESPACE
    - --context
    - $CONTEXT
  get-all:
    shortCut: g
    confirm: false
    description: get-all
    scopes:
    - all
    command: sh
    background: false
    args:
    - -c
    - kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -n $NAMESPACE | less
  # View user-supplied values when the helm chart was created
  helm-values:
    shortCut: v
    confirm: false
    description: Values
    scopes:
    - helm
    command: sh
    background: false
    args:
    - -c
    - "helm get values $COL-NAME -n $NAMESPACE --kube-context $CONTEXT | less"
  toggleCronjob:
    shortCut: Ctrl-S
    confirm: true
    scopes:
      - cj
    description: Toggle to suspend or resume a running cronjob
    command: kubectl
    background: true
    args:
      - patch
      - cronjobs
      - $NAME
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
      - -p
      - '{"spec" : {"suspend" : $!COL-SUSPEND }}'
  # watch events on selected resources
  # requires linux "watch" command
  # change '-n' to adjust refresh time in seconds
  #watch-events:
  #  shortCut: Shift-E
  #  confirm: false
  #  description: Get Events
  #  scopes:
  #  - all
  #  command: sh
  #  background: false
  #  args:
  #  - -c
  #  - "watch -n 5 kubectl get events --context $CONTEXT --namespace $NAMESPACE --field-selector involvedObject.name=$NAME"
  node-shell:
    shortCut: s
    confirm: false
    description: node-shell
    scopes:
    - node
    command: kubectl
    background: false
    args:
    - node-shell
    - $NAME
    - --context
    - $CONTEXT
  debug-shell:
    shortCut: Shift-B
    description: Debug shell
    scopes:
    - containers
    command: kubectl
    background: false
    args:
    - debug
    - -it
    - $POD
    - --image=alpine:edge
    - --target=$NAME
    - -n
    - $NAMESPACE
    - --context
    - $CONTEXT
  debug-copy:
    shortCut: Shift-G
    description: Debug copy
    scopes:
    - po
    command: bash
    background: true
    args:
    - -c
    - "kubectl delete pod -n $NAMESPACE $NAME-debug --grace-period=0; kubectl debug $NAME -ti --attach=false --image=alpine:edge --share-processes --copy-to $NAME-debug -n $NAMESPACE --context $CONTEXT"
