# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: let
  luksDev = {
    root = "root";
    home-leila = "home-leila";
    swap = "swap";
  };

  mkBcachefsMount = {subdir, ...} @ args: let
    luksDep = lib.pipe config.boot.initrd.luks.devices [
      lib.attrNames
      (lib.filter (lib.hasPrefix "bcachefs"))
      (lib.map (n: [
        # n must not contain any dashes as thouse would have to be escaped
        "x-systemd.requires=dev-mapper-${n}.device"
        "x-systemd.after=dev-mapper-${n}.device"
      ]))
      lib.flatten
    ];
  in
    (lib.filterAttrs (n: _: n != "subdir") args)
    // {
      device = "/dev/disk/by-uuid/273588c1-9520-418a-a588-ff7ea33a0c9a";
      fsType = "bcachefs";
      options = ["X-mount.subdir=${subdir}"] ++ luksDep ++ (args.options or []);
    };

  mkSteamMountpoint = username: {
    "/home/${username}/.local/share/Steam" = let
      user = config.users.users.${username};
      group = config.users.groups.${user.group};
      idmapOption = uid: gid:
        "X-mount.idmap="
        + lib.concatStringsSep "\\040" [
          "u:0:${toString uid}:1"
          "g:0:${toString gid}:1"
        ];
    in
      mkBcachefsMount {
        subdir = "Steam";
        options = [
          (idmapOption user.uid group.gid)
        ];
      };
  };
in {
  boot.initrd.luks.devices."${luksDev.home-leila}".device = "/dev/disk/by-uuid/ae264b70-6cfc-49e3-9777-213e0c1b6169";
  boot.initrd.luks.devices."${luksDev.swap}".device = "/dev/disk/by-uuid/7dfd5430-906b-4826-a38a-0fcb0818c1ad";
  boot.initrd.luks.devices.bcachefs1.device = "/dev/disk/by-uuid/b7bf7aea-599c-4ea4-8e3b-d65dc718db30";
  boot.initrd.luks.devices.bcachefs2.device = "/dev/disk/by-uuid/21c65b6f-1169-41e9-a8ad-f011ee288bf9";
  boot.initrd.luks.devices.bcachefs3.device = "/dev/disk/by-uuid/b2aca9eb-ad47-41b8-88b2-da461dae330f";
  boot.initrd.luks.devices.bcachefs4.device = "/dev/disk/by-uuid/22a113fb-fd79-40bf-8d28-53abe042fcef";

  fileSystems =
    {
      "/" = mkBcachefsMount {subdir = "rootvol";};
      "/nix" = mkBcachefsMount {subdir = "nix";};
      "/home" = mkBcachefsMount {subdir = "home";};

      "/boot" = {
        device = "/dev/disk/by-uuid/5A8B-57C3";
        fsType = "vfat";
        options = ["umask=0077"];
      };

      "/home/leila" = {
        device = "/dev/mapper/${luksDev.home-leila}";
        fsType = "ext4";
        options = ["X-mount.subdir=leila"];
      };
    }
    // (lib.foldl' (acc: username: acc // mkSteamMountpoint username) {} ["silvio" "gamer" "mine" "leila"]);

  swapDevices = [
    {
      device = "/dev/mapper/${luksDev.swap}";
    }
  ];
  boot.resumeDevice = "/dev/mapper/${luksDev.swap}";
}
