name: "Check"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - uses: cachix/cachix-action@v14
      with:
        name: lykos153
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check --print-build-logs
