name: "Nix build system"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-system:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v14
      with:
        name: lykos153
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix run nixpkgs#nixos-rebuild -- build --flake .#silvio-pc
    - run: nix run nixpkgs#nixos-rebuild -- build --flake .#silvio-ch
