name: "Nix build user sa"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-user:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v14
      with:
        name: lykos153
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix run nixpkgs#home-manager -- build --flake .#sa@silvio-ch
